name: Publish Package
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install --upgrade setuptools wheel twine

      - name: Extract tag version
        id: extract_version
        run: echo ::set-output name=version::${{ github.ref }}

      - name: Build package
        run: |
          cd /home/runner/work/PlanBee/
          python setup.py --version ${{ steps.extract_version.outputs.version }} sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
