name: Publish Package
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install --upgrade setuptools wheel twine

      - name: Extract tag version
        id: extract_version
        run: echo ::set-output name=version::${{ github.ref }}

      - name: Build package
        working-directory: ${{ github.workspace }}
        run: |
          version=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
          python setup.py --version $version sdist bdist_wheel
          echo "::set-env name=PKG_VERSION::$version"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
